alter session enable shard ddl;
-- USER SQL
CREATE USER "EXAMPLE_USER" IDENTIFIED BY "welcome1"  ;

-- QUOTAS

-- ROLES
GRANT "CONNECT" TO "EXAMPLE_USER" ;
GRANT "RESOURCE" TO "EXAMPLE_USER" ;

-- SYSTEM PRIVILEGES
GRANT CREATE TABLESPACE TO "EXAMPLE_USER" ;
GRANT CREATE ANY TABLE TO "EXAMPLE_USER" ;
grant unlimited tablespace to example_user;
GRANT CREATE ANY MATERIALIZED VIEW TO "EXAMPLE_USER" ;
GRANT CREATE ANY VIEW TO "EXAMPLE_USER" ;
GRANT CREATE DATABASE LINK TO "EXAMPLE_USER" ;
GRANT CREATE MATERIALIZED VIEW TO "EXAMPLE_USER" ;

