#
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-pvc
  labels:
    app: oracledb
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: pure
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: orcldb
  labels:
    app: oracledb
  annotations:
    maintainer: _BA-IT-Systemhaus-SEAQ1 <IT-Systemhaus.SEAQ1@arbeitsagentur.de>
    skipBnfas: "BaseImageValidator,SDCValidator"
spec:
  selector:
    matchLabels:
      app: oracledb
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: oracledb
    spec:
      containers:
      - env:
#         Sets the password for sys, system and pdb_admin 
        - name: ORACLE_PWD
          value: "welcomeSEAQ1"
        - name: ORACLE_PDB
          value: "SEAQ1PDB" 
        image: registry-thf.idst.ibaintern.de:5050/seaq1/sharding/oracle/database:19.3.0-ee 
        name: orcldb
        ports:
        - containerPort: 1521
          name: orcldb
        volumeMounts:
        - name: data
          mountPath: /opt/oracle/oradata/ 
        readinessProbe:
          tcpSocket:
            port: 1521
          initialDelaySeconds: 300
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 1521
          initialDelaySeconds: 15
          periodSeconds: 20
        resources:
          limits:
            cpu: 2000m
            memory: 6Gi
          requests:
            cpu: 1000m
            memory: 4Gi
      imagePullSecrets:
        - name: registry
      securityContext:
        runAsNonRoot: true
        runAsUser: 54321
        fsGroup: 54321
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: data-pvc
---
apiVersion: v1
kind: Service
metadata:
 name: oracledb
spec:
 type: NodePort
 selector:
   app: oracledb
 ports:
   - name: client
     protocol: TCP
     port: 1521
#     nodePort: 31233
 selector:
   app: oracledb
